version: '3'
services:
  
  # front:
  #   image: agus-angular
  #   container_name: frontend
  #   volumes:
  #     - .:/app
  #   ports:
  #    - 4200:80
   
  back:
    image: agus-nestjs
    container_name: backend
    volumes:
      - '.:/opt/tienda' 
    ports:
      - 3000:3000

  database:
    image: 'postgres:latest'
    container_name: database
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'

  # adminer:
  #   image: adminer:latest
  #   ports:
  #     - 8080:8080