version: '3'
services:
  
  front:
    image: agus-angular
    container_name: frontend
    ports:
      - 4200:4200
    volumes:
      - .:/opt/app
    working_dir: '/opt/app'
  
  back:
    image: pagustin/agus-nestjs
    container_name: backend
    volumes:
      - '.:/opt/tienda' 
    ports:
      - 3000:3000
    working_dir: '/opt/tienda'  

  database:
    image: 'postgres:latest'
    container_name: database
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080