version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=agustin
      - POSTGRES_DB=Tienda
      - POSTGRES_PASSWORD=12345
    ports:
      - '5432:5432'

  adminer:
    image: 'adminer:latest'
    ports:
      - '8080:8080'