apiVersion: v1
kind: Service
metadata:
  name: nest
  labels:
    app: nest
spec:
  type: NodePort
  selector:
    app: nest
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
    
    