name: Build and Deploy to Docker

on:
  release:
    types: [created]

env:
  NAME: pagustin/agus-nestjs
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  tests:
    uses: PieresAgustin/Tienda-Web-NestJS/.github/workflows/tests.yml@main

  build:
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - uses: actions/checkout@v3

      - name: 'Build the Docker image'
        run: 'docker build . -t ${{ env.NAME }}'

      - name: 'Login to Docker Hub'
        run: 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
        
      - name: 'Push Docker images'
        run: 'docker push -a ${{ env.NAME }}'
