name: Build Images and Deploy

on:
  release:
    types: [published]

env:
  NAME: pagustin/agus-nestjs

jobs:
  run-tests:
    uses: pieresagustin/tienda-web-nestjs/.github/workflows/tests.yml@main

  build:
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - uses: actions/checkout@v3

      - name: 'Build the Docker image'
        run: 'docker build . -t ${{ env.NAME }}'

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: 'Push Docker images'
        run: 'docker push -a ${{ env.NAME }}'
